# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('chegada', models.TimeField()),
                ('saida', models.TimeField(null=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('tarefa', models.TextField(blank=True, null=True, verbose_name='Tarefa')),
                ('beneficiado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Beneficiado')),
            ],
        ),
    ]
